config/routes.rb
Rails.application.routes.draw do
  resources :inquiry_item_prices
  resources :inquiry_items
  resources :inquiries

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  has_many :inquiry_items

  accepts_nested_attributes_for :inquiry_items
end

app/models/inquiry_item.rb
class InquiryItem < ActiveRecord::Base
  belongs_to :inquiry
  has_many :inquiry_item_prices

  accepts_nested_attributes_for :inquiry_item_prices
end

app/models/inquiry_item_price.rb
class InquiryItemPrice < ActiveRecord::Base
  belongs_to :inquiry_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
    @inquiry = Inquiry.find(params[:id])
    @inquiry.inquiry_items.each { |item| item.inquiry_item_prices.build }
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:name)
    end
end

app/controllers/inquiry_item_prices_controller.rb
class InquiryItemPricesController < ApplicationController
  before_action :set_inquiry_item_price, only: [:show, :edit, :update, :destroy]

  # GET /inquiry_item_prices
  # GET /inquiry_item_prices.json
  def index
    @inquiry_item_prices = InquiryItemPrice.all
  end

  # GET /inquiry_item_prices/1
  # GET /inquiry_item_prices/1.json
  def show
  end

  # GET /inquiry_item_prices/new
  def new
    @inquiry_item_price = InquiryItemPrice.new
  end

  # GET /inquiry_item_prices/1/edit
  def edit
  end

  # POST /inquiry_item_prices
  # POST /inquiry_item_prices.json
  def create
    @inquiry_item_price = InquiryItemPrice.new(inquiry_item_price_params)

    respond_to do |format|
      if @inquiry_item_price.save
        format.html { redirect_to @inquiry_item_price, notice: 'Inquiry item price was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry_item_price }
      else
        format.html { render :new }
        format.json { render json: @inquiry_item_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiry_item_prices/1
  # PATCH/PUT /inquiry_item_prices/1.json
  def update
    respond_to do |format|
      if @inquiry_item_price.update(inquiry_item_price_params)
        format.html { redirect_to @inquiry_item_price, notice: 'Inquiry item price was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry_item_price }
      else
        format.html { render :edit }
        format.json { render json: @inquiry_item_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiry_item_prices/1
  # DELETE /inquiry_item_prices/1.json
  def destroy
    @inquiry_item_price.destroy
    respond_to do |format|
      format.html { redirect_to inquiry_item_prices_url, notice: 'Inquiry item price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry_item_price
      @inquiry_item_price = InquiryItemPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_item_price_params
      params.require(:inquiry_item_price).permit(:amount, :inquiry_item_id)
    end
end

app/controllers/inquiry_items_controller.rb
class InquiryItemsController < ApplicationController
  before_action :set_inquiry_item, only: [:show, :edit, :update, :destroy]

  # GET /inquiry_items
  # GET /inquiry_items.json
  def index
    @inquiry_items = InquiryItem.all
  end

  # GET /inquiry_items/1
  # GET /inquiry_items/1.json
  def show
  end

  # GET /inquiry_items/new
  def new
    @inquiry_item = InquiryItem.new
  end

  # GET /inquiry_items/1/edit
  def edit
  end

  # POST /inquiry_items
  # POST /inquiry_items.json
  def create
    @inquiry_item = InquiryItem.new(inquiry_item_params)

    respond_to do |format|
      if @inquiry_item.save
        format.html { redirect_to @inquiry_item, notice: 'Inquiry item was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry_item }
      else
        format.html { render :new }
        format.json { render json: @inquiry_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiry_items/1
  # PATCH/PUT /inquiry_items/1.json
  def update
    respond_to do |format|
      if @inquiry_item.update(inquiry_item_params)
        format.html { redirect_to @inquiry_item, notice: 'Inquiry item was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry_item }
      else
        format.html { render :edit }
        format.json { render json: @inquiry_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiry_items/1
  # DELETE /inquiry_items/1.json
  def destroy
    @inquiry_item.destroy
    respond_to do |format|
      format.html { redirect_to inquiry_items_url, notice: 'Inquiry item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry_item
      @inquiry_item = InquiryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_item_params
      params.require(:inquiry_item).permit(:name, :inquiry_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/inquiry_item_prices_helper.rb
module InquiryItemPricesHelper
end

app/helpers/inquiry_items_helper.rb
module InquiryItemsHelper
end

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.name %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<h1>New Inquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inquiry.name %>
</p>

<%= form_for(@inquiry) do |f| %>
  <table>
    <thead>
      <tr>
        <td>Name</td>
        <td>Value</td>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for(:inquiry_items) do |item_form| %>
        <tr>
          <td><%= item_form.object.name %></td>
          <%= item_form.fields_for(:inquiry_item_prices) do |price_form| %>
            <td><%= price_form.text_field :price %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= f.submit "Save" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FieldsForExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>